# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Evan Savage
# email: your-email@example.com
description: S4V4GE
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://evan-savage.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
location: Philadelphia, PA
github_username:  evansavage
linkedin_username: evan-savage-45050694
soundcloud_username: s4v4ge1
instagram_username: _s4v4ge
bandcamp_username: s4v4ge # replace with your_twitter_username or comment to remove link from footer
ra_username: s4v4ge
email: esav678@gmail.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  cards:
    output: true
  cards_2:
    output: true
  music_cards:
    output: true

logo: /assets/img/20_03_05-sq-logo-4.png

social:
  name: Evan Savage
  links:
    - https://www.linkedin.com/in/evan-savage-45050694
    - https://github.com/evansavage

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
